const {
  API_URL,
  API_TOKEN,
  API_DEV_STORAGE,
  REDIS_URL,
  GCP_CREDENTIALS_PROJECT_ID,
  GCP_CREDENTIALS_PRIVATE_KEY_ID,
  GCP_CREDENTIALS_PRIVATE_KEY,
  GCP_CREDENTIALS_CLIENT_EMAIL,
  GCP_CREDENTIALS_CLIENT_ID,
  COLI_DISCORD_WEBHOOK,
} = process.env;

export const config = {
  api: {
    URL: API_URL,
    TOKEN: API_TOKEN,
    DEV_STORAGE: API_DEV_STORAGE,
  },
  redis: {
    URL: REDIS_URL,
  },
  gcp: {
    credentials: {
      PROJECT_ID: GCP_CREDENTIALS_PROJECT_ID,
      KEY_ID: GCP_CREDENTIALS_PRIVATE_KEY_ID,
      KEY: GCP_CREDENTIALS_PRIVATE_KEY,
      CLIENT_EMAIL: GCP_CREDENTIALS_CLIENT_EMAIL,
      CLIENT_ID: GCP_CREDENTIALS_CLIENT_ID,
    },
  },
  coli: {
    DISCORD_WEBHOOK: COLI_DISCORD_WEBHOOK,
  },
};
