#?: Use native ports (3000, 6379)

networks:
  coli-prd-coliburgers:
    driver: bridge

services:
  web:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: coli-prd-coliburgers-web
    container_name: coli-prd-coliburgers-web
    ports:
      - "3003:3000"
  redis:
    image: redis:alpine
    container_name: coli-prd-coliburgers-redis
    ports:
      - "6382:6379"
