networks:
  coli-stg-coliburgers:
    driver: bridge

services:
  web:
    build:
      context: ../../
      dockerfile: docker/staging/Dockerfile
    image: coli-stg-coliburgers-web
    container_name: coli-stg-coliburgers-web
    ports:
      - "3002:3000"
  redis:
    image: redis:alpine
    container_name: coli-stg-coliburgers-redis
    ports:
      - "6381:6379"
